Weekly view front end
Qtipshooter/taskbook-SWE pull request #127
Opened 2022-02-11 22:18 UTC by SeanDonnelly1

-Replaced dropdowns with accordion
-Moved CSS to styles.css
-Moved add task, monthly/task view buttons to bottom of page to match the rest of the site

2022-02-12 04:55 UTC, sagarsubedi requested changes

2022-02-12 04:55 UTC, sagarsubedi commented on templates/weekly.html
>  <script>
Do we still need this?

2022-02-12 04:55 UTC, sagarsubedi commented on templates/weekly.html
> +<div class="container">
This accordion code is repeated a lot. Is there any way to minimize the repeated code?

2022-02-12 04:55 UTC, sagarsubedi commented on static/styles.css
> +  .dropdown {
Do we need any of these dropdown styles? I do not see any dropdown class in weekly.html file

2022-02-12 04:55 UTC, sagarsubedi commented on static/styles.css
> +  .days {
There already seems to be a day class on calendar.html, could you clarify why this style exists?

2022-02-12 17:21 UTC, SeanDonnelly1 commented on static/styles.css
> +  .days {
I believe this was also used for the dropdowns. It was to apply CSS to the buttons for each day without changing how the content inside the dropdown would look. We most likely won't need this anymore, so I can delete this part

2022-02-12 17:27 UTC, SeanDonnelly1 commented on templates/weekly.html
> +<div class="container">
I would have liked to use a loop or something for this, but each day in the accordion needs to have its own set of variables to work correctly. Otherwise, you'll have problems such as all sections of the accordion opening and closing at the same time when any one of them is clicked. I know the way I did it is messy, but I couldn't think of another way around this issue. Hopefully next sprint we can find some way to make this cleaner.

2022-02-12 20:05 UTC, Qtipshooter commented on templates/weekly.html
> +<div class="container">
Yea, looking at this for sure this can be made with a variable to assign things such as IDs or such.  Even if we just move some parts of it.  Why were multiple opening and closing at the same time?

2022-02-12 22:04 UTC, Qtipshooter commented on templates/weekly.html
> +          <p>[Insert task here]</p>
The new accordion looks good while not repeating as much code.  Don't forget to add dummy data here as well

2022-02-13 19:56 UTC, sagarsubedi commented on templates/weekly.html
> +  <h1>January 30 - February 5</h1>
@SeanDonnelly1 @ebradd5 Could we make this range of date dynamic depending on what week this is instead of just saying January 30 - February 5?

2022-02-17 21:57 UTC, Qtipshooter commented on static/week-view.js
> +const firstDay = new Date(date.getTime() - 60*60*24*day*1000);
I'm kinda confused how this is returning the first day and last day of the week.  Could you explain the magic numbers?

2022-02-17 21:57 UTC, Qtipshooter commented on templates/weekly.html
> +<div class="container">
This was resolved with the loop if I recall

2022-02-17 22:09 UTC, SeanDonnelly1 commented on static/styles/styles.css
> +    .accordion {
I don't think we'll have an accordion on any other pages, so it should be fine to move it into its own file. I'll do that next time I work on it.

2022-02-17 22:26 UTC, Qtipshooter commented on static/week-view.js
> +const firstDay = new Date(date.getTime() - 60*60*24*day*1000);
It still kinda has me confused.  From looking at it, I would assume that one 60 is minutes, one 60 is seconds, 24 is hours, but that doesn't make sense how it gets the Sunday of the week by multiplying that with the arbitrary number 1000 and the current number of the day.

2022-02-18 21:31 UTC, Qtipshooter commented on templates/weekly.html
> +            <p class="task-header">yyyy-mm-dd | hh:mm</p>
Would it be a better idea to put these into some kind of div?  It looks like if there was more than one task that it would look funky and just kinda clash.  None of them have a second task on them though, so I am not sure.

2022-02-18 21:33 UTC, Qtipshooter commented on static/scripts/week-view.js
> +const firstDay = new Date(date.getTime() - 60*60*24*day*1000);
I'm not sure what this code here is doing, there are just a bunch of magic numbers.  Would you be able to elaborate on what the numbers mean?  I think I can guess for all of them except the 1000, but it just seems so arbitrary and doesn't make sense.

2022-02-18 21:59 UTC, sagarsubedi reviewed
The only thing that would be functionally important here is how a task or group of tasks will look inside the accordion. Could you please work on that? And rest of the suggestions, you can ignore if you want or work on them as well. Rest aren't functional requirement

2022-02-18 21:59 UTC, sagarsubedi commented on static/styles/weekly.css
> +.accordion {
The new styles I have recommended might clash with some of the ones present here, just an FYI.

2022-02-18 21:59 UTC, sagarsubedi commented on templates/weekly.html
> +            <p class="task-header">yyyy-mm-dd | hh:mm</p>
Yes, a div is exactly what I was suggesting - something to clearly differentiate multiple tasks in a single week. Also, a task taking up the entire width seemed a bit off.

2022-02-18 21:59 UTC, sagarsubedi commented on static/scripts/week-view.js
> +const firstDay = new Date(date.getTime() - 60*60*24*day*1000);
I agree. This is forcing a developer to look up what getTime() returns and then try to make sense of substracting the result of 60\*60\*24\*day\*1000 from getTime(). I know what getTime() returns but it is still unclear how this returns the firstDay of the week. Instead of explaining to us or putting a lengthy comment, it might be a good idea to clean up line 23 and 26. Just a suggestion.

2022-02-19 20:54 UTC, Qtipshooter commented on static/scripts/week-view.js
> +//will return last day of the week in milliseconds (Saturday)
Oh, okay.  I think it makes a bit more sense now.  We can edit it to remove magic numbers later.

2022-02-19 21:00 UTC, Qtipshooter approved these changes
Okay, looks like it is something we can work with.  We just will have to make a new function that is slightly different than the old one.

2022-02-20 01:49 UTC, sagarsubedi approved these changes
Looks good. I think Sean still wanted to change the accordion background when clicked. Other than that, I think the front-end is now fine and the back-end person can start working on this.

2022-02-20 01:54 UTC, merged