Errorhandling
Qtipshooter/taskbook-SWE pull request #145
Opened 2022-02-21 19:47 UTC by Dorugoramon

Added Error Handling Functionality for 400,404,and 500 errors specifically to redirect users to an error page.

Also added a generic page for all other errors.

Modified app.py
Added new routes for error pages
Added for HTML pages to templates, one for each error

2022-02-21 23:38 UTC, Qtipshooter commented on app.py
> +#400
Why do we need to have routes to each of the error pages?  I don't know why we let the user just go to it because they were hunting for it.

2022-02-22 01:14 UTC, Qtipshooter commented on templates/error500.html
> +</div>
There should also be the footer on each of these pages

2022-02-22 04:08 UTC, Qtipshooter commented on flask_app.py
> +
What is this file here for?

2022-02-22 04:10 UTC, Qtipshooter requested changes
We should have the footers on each of the different error pages, there shouldn't be the flask_app.py by the looks of it, and there should not be routes to reach the error pages directly for users (This is fine while working, but should not be pushed to main)

2022-02-22 13:40 UTC, Dorugoramon commented on templates/error500.html
> +</div>
Added footer include

2022-02-22 13:40 UTC, Dorugoramon commented on flask_app.py
> +
Deleted

2022-02-22 13:42 UTC, Dorugoramon reviewed
Made suggested changes to html pages. 

Deleted flask_app.py

2022-02-24 03:22 UTC, sagarsubedi commented on app.py
> +#400
Why was this conversation resolved? @Dorugoramon

2022-02-24 13:06 UTC, Qtipshooter commented on app.py
> +#400
We should be able to remove these, so is there some other reason we should have these?  If not, this is not resolved

2022-02-24 13:13 UTC, Qtipshooter requested changes
The pages look less functional than they were before because they have the footer above the text

2022-02-24 13:13 UTC, Qtipshooter commented on templates/error404.html
> +{% include 'footer.html' %}
Why are the footers before all the text on the page?

2022-02-24 13:13 UTC, Qtipshooter commented on templates/error500.html
> +{% include 'footer.html' %}
Same with all the other pages

2022-02-25 19:40 UTC, Dorugoramon commented on app.py
> +#400
Removed error routes, turns out it work swithout them.

2022-02-25 19:45 UTC, Qtipshooter requested changes
The footers need moved still from where they are.  When looking at the site, you can tell thats not where they should be

2022-02-25 19:45 UTC, Qtipshooter commented on templates/errorpage.html
> +{% include 'footer.html' %}
The footer should still not be at the top of the pages

2022-02-25 19:45 UTC, Qtipshooter commented on templates/error400.html
> +{% include 'footer.html' %}
There are 4 pages with this footer at the top

2022-02-26 17:53 UTC, Dorugoramon commented on templates/error400.html
> +{% include 'footer.html' %}
Moved footer to the bottom

2022-02-27 15:43 UTC, Qtipshooter approved these changes
Okay, that should work to allow the others to work on the front end of it and it work out

2022-02-28 01:10 UTC, sagarsubedi commented
Will close this because a different branch has PR with more updated code.

2022-02-28 01:10 UTC, closed without merging