Calendar view
Qtipshooter/taskbook-SWE pull request #55
Opened 2021-12-14 13:08 UTC by jelbin313

Updates to calendar page, added weekly page

2021-12-15 15:19 UTC, sagarsubedi approved these changes

2021-12-15 23:00 UTC, sagarsubedi requested changes
I left my comments. There are some tweaks that need to be made. Once we have a common agreement on the changes I requested, we can then merge.

2022-01-04 20:47 UTC, Qtipshooter commented on static/calendar-style.css
> +.prev-days, .next-days {
I will add this into the issues list to leave this up to the people doing this page

2022-01-04 20:58 UTC, Qtipshooter approved these changes

2022-01-13 14:47 UTC, sagarsubedi approved these changes

2022-01-13 14:47 UTC, merged